### ISSUE TITLE
I have an error when run cargo build

### ISSUE THREAD

**Issue by marti1125** [teisenbe/rust-traceroute#1]
Help me please.

Compiling traceroute v0.1.1 (file:///Users/willyaguirre/Documents/rust-traceroute)
src/lib.rs:228:31: 228:53 error: no associated item named `InvalidData` found for type `std::io::error::ErrorKind` in the current scope
src/lib.rs:228         return Err(Error::new(ErrorKind::InvalidData, "Packet too short"));
                                             ^~~~~~~~~~~~~~~~~~~~~~
src/lib.rs:232:31: 232:53 error: no associated item named `InvalidData` found for type `std::io::error::ErrorKind` in the current scope
src/lib.rs:232         return Err(Error::new(ErrorKind::InvalidData, "Packet too short"));
                                             ^~~~~~~~~~~~~~~~~~~~~~
src/lib.rs:241:18: 241:33 error: mismatched types:
 expected `i32`,
    found `i64`
(expected i32,
    found i64) [E0308]
src/lib.rs:241         tv_usec: usecs % 1000000
                                ^~~~~~~~~~~~~~~
src/lib.rs:241:18: 241:33 help: run `rustc --explain E0308` to see a detailed explanation
error: aborting due to 3 previous errors
Could not compile `traceroute`.

**Comment by marti1125** [comment]
rustc --version
rustc 1.1.0 (35ceea399 2015-06-19)

**Comment by teisenbe** [comment]
This was developed on rust 1.2, will update the readme

-----Original Message-----

**Comment by marti1125** [comment]
updating rust version =D

**Comment by marti1125** [comment]
error is aboyt type...

Compiling traceroute v0.1.1 (file:///Users/willyaguirre/Documents/rust-traceroute)
src/lib.rs:241:18: 241:33 error: mismatched types:
 expected `i32`,
    found `i64`
(expected i32,
    found i64) [E0308]
src/lib.rs:241         tv_usec: usecs % 1000000
                                ^~~~~~~~~~~~~~~
src/lib.rs:241:18: 241:33 help: run `rustc --explain E0308` to see a detailed explanation
error: aborting due to previous error
Could not compile `traceroute`.

$ rustc --version
rustc 1.2.0 (082e47636 2015-08-03)

**Comment by teisenbe** [comment]
Huh, will investigate.

-----Original Message-----

**Comment by marti1125** [comment]
I am rust stable version in Mac OS 10.10.5

**Comment by teisenbe** [comment]
Hmm, this actually seems to come down to a difference in types in the libc crate between x86 and x86_64.  I just pushed a change that should fix it (b96a29256af1edf8f79c9011fefea3d4a17d1862).  Can you confirm that this fixes it, and if so I'll publish to Cargo

**Comment by teisenbe** [comment]
Err, nevermind, try a8b9f70d9998746839893cf314911bb66d1b35f3.  Set up an x86 environment and confirmed it compiles and runs correctly with that (I don't have an OS X box to test on though).

**Comment by marti1125** [comment]
Cargo build works perfectly

**Comment by marti1125** [comment]
when I tried to run:  $ cargo run
   Compiling traceroute v0.1.2 (file:///Users/willyaguirre/Documents/rust-traceroute)
     Running `target/debug/traceroute`
thread '<main>' panicked at 'called `Option::unwrap()` on a `None` value', ../src/libcore/option.rs:362 

(in other issue...) I am going to install rust in my ubuntu virtual machine for test

**Comment by teisenbe** [comment]
Ah, that unwrap is probably just from you not specifying a host to trace.  The lib shouldn't be calling unwrap without knowing for certain that the value is a Some

-----Original Message-----

**Comment by marti1125** [comment]
Could you give an example, please? 
willy@willy-VirtualBox:~/rust-traceroute$ cargo run
     Running `target/debug/traceroute`
thread '<main>' panicked at 'called `Option::unwrap()` on a `None` value', ../src/libcore/option.rs:362
An unknown error occurred

**Comment by teisenbe** [comment]
Try: sudo cargo run google.com

-----Original Message-----

**Comment by marti1125** [comment]
I got this....
$ sudo cargo run https://github.com/
     Running `target/debug/traceroute https://github.com/`
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Custom(Custom { kind: Other, error: StringError("failed to lookup address information: nodename nor servname provided, or not known") }) }', ../src/libcore/result.rs:731
An unknown error occurred

To learn more, run the command again with --verbose

**Comment by teisenbe** [comment]
Try with github.com rather than https://github.com.  This deals with hostnames, not URIs.

-----Original Message-----

**Comment by marti1125** [comment]
$ sudo cargo run superuser.com
     Running `target/debug/traceroute superuser.com`
Err(Error { repr: Os { code: 22, message: "Invalid argument" } })

**Comment by teisenbe** [comment]
Huh, I cannot reproduce that one:

 $ sudo cargo run superuser.com
     Running `target/debug/traceroute superuser.com`
Ok(TraceHop { ttl: 1, host: V4(192.168.1.1:0), rtt: Duration { secs: 0,
nanos: 1915127 } })
Ok(TraceHop { ttl: 2, host: V4(67.164.96.1:0), rtt: Duration { secs: 0,
nanos: 9560693 } })
Ok(TraceHop { ttl: 3, host: V4(68.85.103.189:0), rtt: Duration { secs: 0,
nanos: 9709309 } })
Ok(TraceHop { ttl: 4, host: V4(68.85.57.169:0), rtt: Duration { secs: 0,
nanos: 14439109 } })
Ok(TraceHop { ttl: 5, host: V4(68.85.57.241:0), rtt: Duration { secs: 0,
nanos: 11151599 } })
Ok(TraceHop { ttl: 7, host: V4(68.86.86.222:0), rtt: Duration { secs: 0,
nanos: 29134308 } })
Ok(TraceHop { ttl: 8, host: V4(129.250.66.33:0), rtt: Duration { secs: 0,
nanos: 33181086 } })
Ok(TraceHop { ttl: 9, host: V4(129.250.207.46:0), rtt: Duration { secs: 0,
nanos: 26971353 } })
Ok(TraceHop { ttl: 10, host: V4(190.93.247.58:0), rtt: Duration { secs: 0,
nanos: 13280232 } })

**Comment by marti1125** [comment]
oh Mac OS problem =/ I am going to close this issue. I will check what is the problem. maybe sent a PR
